apiVersion: v1
kind: Service
metadata:
  name: css-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80   ## Request from external (web broswer)
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: css-app
